spring.application.name=demo

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/board}
spring.datasource.username=${DATABASE_USERNAME:board}
spring.datasource.password=${DATABASE_PASSWORD:board}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml
